# Generated by Django 6.0.4 on 2026-05-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image1', models.ImageField(upload_to='team_image/%y/%m/%d')),
                ('image2', models.ImageField(upload_to='team_image/%y/%m/%d')),
                ('image3', models.ImageField(upload_to='team_image/%y/%m/%d')),
                ('image4', models.ImageField(upload_to='team_image/%y/%m/%d')),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
